# signals.py
# ─────────────────────────────────────────────────────────────────────────────
# Detection signal functions for Provenance Guard.
#
# Currently contains Signal 1 only (Milestone 3).
# Signals 2 and 3 will be appended in Milestone 4.
#
# Signal 1 — get_llm_score(text, content_type)
#   Sends the text to Groq's llama-3.3-70b-versatile with a structured prompt.
#   Steps:
#     1. Build a content-type-aware prompt requesting ai_probability (0.0–1.0)
#     2. Call Groq API at temperature=0.1 for reproducibility
#     3. Strip any markdown fences, parse the JSON response
#     4. Return (ai_probability: float, reasoning: str)
#     5. On any failure, fall back to (0.5, error message) — neutral score
#
# Time:  O(network latency) — typically 0.5–2.5s per call
# Space: O(len(text)) for prompt construction
# ─────────────────────────────────────────────────────────────────────────────

import re
import json
import math
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


# ─── Helper: Sentence Splitter ────────────────────────────────────────────────

def _split_sentences(text: str) -> list[str]:
    """
    Splits text into sentences on .  !  ? boundaries followed by whitespace.
    Filters fragments shorter than 3 characters (punctuation artifacts).
    Time: O(n) where n = len(text)
    """
    parts = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s.strip() for s in parts if len(s.strip()) >= 3]


# ─── Signal 1: LLM Classification (Groq) ──────────────────────────────────────

def get_llm_score(text: str, content_type: str = "text") -> tuple[float, str]:
    """
    SIGNAL 1 — Semantic/holistic AI detection via Groq LLM.

    This is the only signal with semantic understanding — it can recognize
    meaning-level patterns (hedged language, topic structure, unnatural polish)
    that purely statistical signals cannot capture.

    Args:
        text:         Content to classify
        content_type: "text" (default prose) or "image_description" (stretch: multi-modal)

    Returns:
        (ai_probability: float 0.0–1.0,  reasoning: str)
        Higher score = more AI-like

    Time:  O(network) — Groq API call
    Space: O(len(text)) for prompt string
    """
    # Adjust prompt framing based on content type (stretch: multi-modal support)
    type_context = {
        "text":              "creative or expository prose (poem, short story, blog post, essay)",
        "image_description": "a written description or caption for an image"
    }.get(content_type, "text")

    prompt = f"""You are an expert at identifying whether text was written by a human or generated by an AI model.

Analyze the following {type_context} and assess whether it was written by a human or AI-generated.

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"

Consider these factors:
1. Stylistic naturalness — AI tends to sound polished, hedged, and structurally balanced
2. Vocabulary choices — humans are more variable; AI favors formal, transition-heavy language
3. Emotional authenticity — humans use colloquialisms, personal anecdotes, irregular rhythm
4. Structural patterns — AI often writes in tidy parallel paragraphs
5. Idiosyncratic markers — typos, fragments, personal voice, unexpected word choices are human signals

Respond with ONLY a JSON object in this exact format (no preamble, no markdown fences):
{{"ai_probability": <float 0.0 to 1.0>, "reasoning": "<one concise sentence>"}}

Where ai_probability means:
  1.0 = almost certainly AI-generated
  0.5 = genuinely uncertain
  0.0 = almost certainly human-written"""

    try:
        response = _client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,    # low temperature → consistent, reproducible scores
            max_tokens=150
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown fences if the model wrapped the JSON in ```json ... ```
        raw = re.sub(r"```json|```", "", raw).strip()

        result = json.loads(raw)
        score     = float(result.get("ai_probability", 0.5))
        reasoning = result.get("reasoning", "No reasoning provided.")

        # Clamp to [0.0, 1.0] in case the model returns a value slightly outside range
        return max(0.0, min(1.0, score)), reasoning

    except json.JSONDecodeError as e:
        return 0.5, f"LLM parse error: {str(e)}"
    except Exception as e:
        return 0.5, f"LLM signal failed: {str(e)}"